---
# Ansible collection dependencies for declercklouis.collection_networking
# Install with: ansible-galaxy collection install -r requirements.yml
collections:
  - name: fortinet.fortios
    version: ">=2.3.0"
  - name: community.routeros
    version: ">=2.0.0"
  - name: community.general
    version: ">=8.0.0"
